name: CCustomores
version: 1.0
main: org.charlie.cCustomores.CCustomores
api-version: 1.20
commands:
  ccustomore:
    description: Main command for the CCustomores plugin.
    permission: ccustomores.reload
permissions:
  ccustomores.reload:
    description: Allows the player to reload the CCustomores plugin configuration.
    default: op
